# simple docker compose for setting up mongodb and logstash

services:
  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   # volumes:
  #   #   - ./data:/data/db
  #   # command: mongod --smallfiles
  auth-server:
    build: demo-auth-server
    ports:
      - "5000:5000"
    networks:
      - eliav-network
  logstash:
    # image: try-logstash:latest
    build: 
      context: logstash
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - eliav-network
#    command: logstash --config.test_and_exit -f /path/to/config/file
    # tty: true
  # beats:
  #   image: docker.elastic.co/beats/filebeat:8.6.2 
  #   depends_on:
  #     - logstash
  #   volumes:
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
networks:
  eliav-network:
    external: true